### ISSUE TITLE
Document dependencies

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/domdb#29]
There are dependencies required to run the code; document them on the Wiki.

**Comment by KujawinskiLaboratory** [comment]
Can you please also add information on the following commands to the wiki:
dir, add_dir
Thanks.

**Comment by joefutrelle** [comment]
Done

**Comment by joefutrelle** [comment]
Looks like readline is not required on Linux; command-line completion works without it installed. The only dependency seems to be SQLAlchemy. This is addressed in the Vagrantfile.
