### ISSUE TITLE
list_attr should not list 'ignore' as attribute

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [joefutrelle/domdb#44]
I like the list_attr command since it makes it easy to remember what the options are. However, can we please remove 'ignore' as an attribute since that will always be zero (or at least it should be if the add_dir code is working!)?

**Comment by joefutrelle** [comment]
This is related to #41

**Comment by KujawinskiLaboratory** [comment]
This is back with the cli.py version of the code.

**Comment by joefutrelle** [comment]
`list_attrs` is not implemented in the new CLI--I can port the code from the old version.

**Comment by KujawinskiLaboratory** [comment]
I should have been clearer...in the new version of the code, the ignore attribute appears when you run 'samples experimentName'.

**Comment by joefutrelle** [comment]
Just noticed that, I'll open that as a separate issue.
