### ISSUE TITLE
export parameters

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [joefutrelle/domdb#47]
One item we had talked about was exporting the search parameters along with the data file. I am putting this here to make sure the idea does not get lost. For example, right now I do this:

> search 505.3343 1012 dataOut.csv

Ultimately I would like to see this spit out two files, one is the data ('dataOut.csv') and the other is the search parameters that were in play when the search was done (perhaps: 'dataOut_parameters.csv'). The pieces that I would like to track are all in the 'config' option right now.

**Comment by KujawinskiLaboratory** [comment]
I thought about this a bit more and realized that you might be able to put this information into a header in dataOut.csv. If you can, that seems easier because it will be one less file to track down.

**Comment by KujawinskiLaboratory** [comment]
The header is fine. But the 'ignore' variable is being exported again (see #66)

**Comment by joefutrelle** [comment]
You mean it's in the CSV output, right? On it.

**Comment by KujawinskiLaboratory** [comment]
Right, 'ignore' in the CSV output.

**Comment by KujawinskiLaboratory** [comment]
All set.
