### ISSUE TITLE
update new cli.py to access positive or negative ion mode database

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [joefutrelle/domdb#50]
With the new version, we can't 'cheat' and have two different folders. So, we now need to have a new version of the database code which will require users to specify up front as to whether they are querying positive or negative ion mode data.

**Comment by KujawinskiLaboratory** [comment]
Also, as part of this, add 'positive' or 'negative' to the parameters exported in the header of the CSV result file.

**Comment by joefutrelle** [comment]
Krista, to test this you will need to delete your database and allow the code to re-create it. The easiest way to do this is from PgadminIII, but it's a little complicated to explain in a github message.

**Comment by KujawinskiLaboratory** [comment]
This works fine and I can add data into two piles: one for pos and one for neg.
