### ISSUE TITLE
can exclude controls even without setting attrs

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [joefutrelle/domdb#55]
If attrs has not been set by a user, I am not sure what 'exclude_controls true' uses to decide upon the controls. I would do two things here. (1) set the default to be 'exclude_controls false'. (2) Set up 'attrs' to be a subheading under 'exclude_controls'. Only if 'exclude_controls' is true should the user be allowed to select the attrs to be used.

**Comment by KujawinskiLaboratory** [comment]
Another way to consider this is to have one 'attr' that is 'any'. Now that I work with this more, I think that will make it less confusing.

**Comment by KujawinskiLaboratory** [comment]
...hold off on this one. As I am working on it, I am not sure my previous thoughts make sense.

**Comment by KujawinskiLaboratory** [comment]
I think we need to set this up as a hierarchy. 
IF exclude_controls is false, the user cannot access 'attrs' or 'int_over_controls'.

IF exclude_controls is true, the user can select from the following:
(1) attrs can be: 'any' or the attributes which are available in the metadata. In the case where the user enters a bogus option (i.e., selects an attribute which does not exist), the code should spit back an error. Right now the code just seems to ignore attributes it does not know how to handle.
(2) int_over_controls can be 'none' or a number value.

**Comment by joefutrelle** [comment]
I think there are multiple issues here, and I'll try to break them out to track them separately.

One comment: with no attrs specified, the behavior of the query is exactly what I think you're asking for with attrs='any'

**Comment by KujawinskiLaboratory** [comment]
Yes, with no attrs specified the query does return what I have labeled as 'any'. However, it took me a few iterations to figure that out.

**Comment by joefutrelle** [comment]
Back to the title of this issue: confirming that was an implementation error on my part and currently controls are always excluded, ignoring the value of the exclude_controls config param.

**Comment by joefutrelle** [comment]
`attrs` now displays as `(any)` if the value is not set.

to set the value to `(any)`, use the command

```
reset attrs
```

rather than

```
set attrs (any)
```

**Comment by KujawinskiLaboratory** [comment]
Looks good.
