### ISSUE TITLE
'match' returns samples with '0' as intensity

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [joefutrelle/domdb#57]
'search' is correctly filtering out the samples which have '0' intensity values. However, 'match' is returning samples where the intensity value is '0'.

**Comment by joefutrelle** [comment]
Both queries contain identical clauses for excluding zero-intensity samples, so they should either both work or both not work.

**Comment by KujawinskiLaboratory** [comment]
There are two files attached here (though I am not sure how GitHub will 
deal with the attachments).

One is 'out_search.csv' which is the output from the 'search ' command. 
Here, you will see that in the intensity column, there are only values 
above 0.

The second file is 'out_match.csv' which is the output from a match 
command. Here, the values in the intensity column can be zero (or 
larger). We do not want to see the results where the intensity in a 
single sample is 0.


On 7/21/2015 12:38 PM, Joe Futrelle wrote:
>
> Both queries contain identical clauses for excluding zero-intensity 
> samples, so they should either both work or both not work.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/joefutrelle/domdb/issues/57#issuecomment-123395861>.
>

-- 
Krista Longnecker
Woods Hole Oceanographic Institution
Marine Chemistry and Geochemistry
Fye 112, MS#4
360 Woods Hole Road
Woods Hole, MA 02543-1541
http://www.whoi.edu/people/klongnecker/

klongnecker@whoi.edu
508 289 2824

**Comment by joefutrelle** [comment]
Github doesn't seem to do attachments, but the only reason I'd need to see the output is if you're reading it wrong, which seems quite unlikely to me--I'm inclined to see if I can reproduce this with the dummy data, and I should be able to pretty easily given your description of the problem.

**Comment by joefutrelle** [comment]
Reviewing the query template, I can see what's wrong with the query. The question is, what is the correct behavior? Should I simply exclude zero-intensity matches, or should the matches be filtered through the entire control exclusion logic that is being used on the experiment being matched from? I think we already discussed this and it's the latter case, but I want to be clear before I begin modifying this query template.

**Comment by KujawinskiLaboratory** [comment]
It is the former case: exclude the zero-intensity matches in the output.

**Comment by joefutrelle** [comment]
Oh, I meant to say the former case. Whew. Should be easy to implement.

**Comment by KujawinskiLaboratory** [comment]
All set.
