### ISSUE TITLE
"search" is slow

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/domdb#58]
I believe the query can be sped up considerably by reordering some of the SQL operations; unclear yet if a similar approach will work for "match".

**Comment by KujawinskiLaboratory** [comment]
Testing out the new search...very fast, but it is giving me empty CSV files that I do not understand. I set 'exclude_controls false' so I could just test the query. If I search for 100 90, I get answers (in out1.csv). However, if I search for 116 100 (in out2.csv) I get no results. My guess is there is some residual control filtering going on in the background.

![capture](https://cloud.githubusercontent.com/assets/9040216/8809621/de13da60-2fb7-11e5-8532-c98eb4def4d8.JPG)

**Comment by joefutrelle** [comment]
Note that `exclude_controls` is still ignored, and controls are still always excluded--that's an already-reported, not-yet-fixed bug.

I tested the new search query against the dummy database and got correct results. Note that in the dummy spreadsheet, metabolite 15 has an mz of 116 and an rt of 90, which matches your query, but it's present int the controls, so you don't get any results unless you set `int_over_controls` to something nonzero.

**Comment by KujawinskiLaboratory** [comment]
OK. I will wait to test the speed on this until the exclude_controls is fixed.

**Comment by KujawinskiLaboratory** [comment]
Speedy and getting answers I expect.
