### ISSUE TITLE
wiki installation instructions need updating

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [joefutrelle/domdb#62]
Right now the installation instructions still describe the vagrant file.

**Comment by joefutrelle** [comment]
I have updated the instructions based on performing a successful Windows installation on a freshly-installed copy of Windows 7. That should address this issue; if there are problems with the instructions we can create new issues for those.

**Comment by KujawinskiLaboratory** [comment]
I will test this out before Monday. If I delete the pages from the wiki 
that are no longer relevant (vagrant installation), is that going to be 
a problem? Also, can you please update the dependencies page?

On 7/31/2015 1:10 PM, Joe Futrelle wrote:
>
> I have updated the instructions based on performing a successful 
> Windows installation on a freshly-installed copy of Windows 7. That 
> should address this issue; if there are problems with the instructions 
> we can create new issues for those.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/joefutrelle/domdb/issues/62#issuecomment-126754853>.
>

-- 
Krista Longnecker
Woods Hole Oceanographic Institution
Marine Chemistry and Geochemistry
Fye 112, MS#4
360 Woods Hole Road
Woods Hole, MA 02543-1541
http://www.whoi.edu/people/klongnecker/

klongnecker@whoi.edu
508 289 2824
